src/_helpers/route.helpers.ts, src/components/TestRunList.tsx, src/pages/ProjectPage.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/10
=> TestRunList. Menu url fixed

src/components/ImageDetails.tsx, src/components/TestDetailsModal.tsx, src/types/testStatus.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/17
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/15
=> TestRun modal. Image details are added

src/components/TestVariationList.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/26
=> Change background-size from cover to contain

src/components/TestDetailsModal.tsx, src/components/TestRunDetails.tsx, src/components/TestVariationDetails.tsx, src/components/TestVariationList.tsx, src/pages/TestVariationDetailsPage.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/27
=> Details title is not shown if empty

src/components/Filters.tsx, src/components/TestRunDetails.tsx, src/components/TestRunList.tsx, src/components/TestVariationDetails.tsx, src/pages/ProjectPage.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/28
=> device info added

src/components/DrawArea.tsx, src/components/TestDetailsModal.tsx, src/index.css
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/21
=> 21 image zoom

src/components/TestDetailsModal.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/24
=> TestRun details. TestVariation link added

src/components/DrawArea.tsx, src/components/Rectangle.jsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/34
=> mouse events are added

src/components/Filters.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/41
=> Filter. Reset button added

package-lock.json, package.json, src/components/Filters.tsx, src/components/SkeletonList.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/42
=> 42 filter debounce

src/_helpers/format.helper.ts, src/components/BuildList.tsx, src/components/DateFormated.tsx, src/pages/ProjectListPage.tsx, src/types/baseline.ts, src/types/build.ts, src/types/project.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/44
=> 44 dateformat

src/contexts/build.context.tsx, src/contexts/socket.context.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/61
=> build update event handle added

src/components/BuildList.tsx, src/pages/ProjectPage.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/75
=> url navigation fixed

README.md, package-lock.json
Visual-Regression-Tracker/Visual-Regression-Tracker#82
=> Local setup doc added

src/components/BuildList.tsx, src/contexts/build.context.tsx, src/contexts/socket.context.tsx, src/services/builds.service.ts, src/types/build.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/57
=> stop build added

.vscode/launch.json, package-lock.json, package.json, src/components/DrawArea.tsx, src/components/TestDetailsModal.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/102
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/55
=> Test run. move image details on canvas

src/components/TestDetailsModal.tsx, src/components/ZoomSpeedDial.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/101
=> Scale related actions are moved into speed dial

src/contexts/socket.context.tsx, src/contexts/testRun.context.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/99
=> testRun_deleted event handle added

src/components/BuildList.tsx, src/components/TestRunList.tsx, src/components/TestVariationList.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/123
=> 123 empty placeholder

src/components/BuildList.tsx, src/types/build.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/2
=> build number added

cypress.json, package-lock.json, package.json, src/components/ApproveRejectButtons.tsx, src/components/ArrowButtons.tsx, src/components/TestDetailsModal.tsx, src/pages/ProjectPage.tsx, src/types/index.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/133
=> Frontend. Hotkeys on TestRun page

src/components/DrawArea.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/134
=> Zoom screenshots with a mouse wheel

src/components/BuildList.tsx, src/pages/ProjectPage.spec.tsx, src/types/build.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/142
=> 142 ci build name

src/pages/TestVariationDetailsPage.tsx
Fix for the issue: https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/67#issuecomment-718596372
=> fix for date format on Test Variation page

src/pages/TestVariationDetailsPage.tsx
Tests for https://github.com/Visual-Regression-Tracker/frontend/pull/98
=> Formatted date

.gitignore, Dockerfile, README.md, docker-compose.yml, nginx/default.conf, package.json
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/125
=> 125 https support

.github/workflows/workflow.yml, cypress.json, package-lock.json, package.json, src/_helpers/precondition.helper.ts, src/_helpers/service.helpers.ts, src/_test/stub.helper.ts, src/_test/test.data.helper.ts, src/components/ProjectSelect.tsx, src/contexts/project.context.tsx, src/pages/LoginPage.spec.tsx, src/pages/ProfilePage.spec.tsx, src/pages/ProfilePage.tsx, src/pages/ProjectListPage.tsx, src/pages/ProjectPage.spec.tsx, src/pages/ProjectPage.tsx, src/pages/RegisterPage.spec.tsx, src/pages/TestVariationDetailsPage.spec.tsx, src/pages/TestVariationListPage.spec.tsx, src/pages/TestVariationListPage.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/150
=> 150 config example

src/components/CommentsPopper.tsx, src/components/DrawArea.tsx, src/components/TestDetailsModal.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/166
=> Image size diff from baseline warning added

src/pages/ProjectPage.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/173
=> Issue #173 - Make filter case insensitive

src/components/TestDetailsModal.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/174  - Add hotkey to close modal
=> Add hotkey to close modal

src/components/ImageDetails.tsx, src/components/TestVariationList.tsx, src/pages/ProjectPage.spec.tsx, src/pages/TestVariationDetailsPage.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/157
=> Image tag added with fit

src/components/BuildList.tsx, src/contexts/build.context.tsx
Fixes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/186
=> Fixes issue #186 : Build details not cleared on deleting a build.

.github/workflows/workflow.yml, cypress.json, cypress/plugins/index.js, package-lock.json, package.json, vrt.json
closes: https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/189
=> Move VRT config to env variables

src/pages/ProjectPage.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/180
=> TestRun filter removed

src/components/ApproveRejectButtons.tsx, src/components/BuildList/index.tsx, src/components/TestDetailsModal.tsx, src/components/TestRunList/BulkDeleteButton.tsx, src/contexts/build.context.tsx, src/contexts/socket.context.tsx, src/contexts/testRun.context.tsx, src/services/testRun.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/212
=> Debounce socket events emit

src/components/TestRunList/index.tsx, src/contexts/build.context.tsx
Fixes issue : https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/234
=> Fix for Issue# 234 : Test run list is not cleared on deleting the last build

src/components/ImageDetails.tsx, src/components/TestDetailsModal.tsx
Fixes issue : https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/211
=> Issue 211 : Remove toggle when no baseline or no diff.

package-lock.json, package.json, src/_helpers/route.helpers.ts, src/components/ArrowButtons.tsx, src/components/BuildList/index.tsx, src/components/TestDetailsDialog/index.tsx, src/components/TestDetailsModal.tsx, src/components/TestRunList/index.tsx, src/components/TestVariationMergeForm.tsx, src/contexts/build.context.tsx, src/contexts/testRun.context.tsx, src/pages/ProjectPage.tsx, src/pages/TestVariationDetailsPage.tsx
closes: https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/240
=> Direct url to testRun does not open modal

src/components/BuildList/index.tsx
Fixes reported issue https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/255
=> Fix of Issue#255 :Changing projects does not refresh the test run screen

src/components/ProjectForm.tsx, src/contexts/project.context.tsx, src/pages/ProjectListPage.tsx, src/services/projects.service.ts, src/types/imageComparison.ts, src/types/project.ts
closes Visual-Regression-Tracker/Visual-Regression-Tracker#215
=> project config

Dockerfile
Recreating this PR https://github.com/Visual-Regression-Tracker/frontend/pull/192 from a branch of the original repository
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/218
=> Run container as non-root

src/components/BuildList/index.tsx, src/components/ProjectForm/ProjectForm.tsx, src/constants/project.ts, src/contexts/build.context.tsx, src/contexts/socket.context.tsx, src/types/project.ts
Addressed reported issue https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/135
=> Issue 135 - Feature to limit number of builds to keep.

src/components/ProjectForm/LooksSameConfigForm.tsx, src/components/ProjectForm/OdiffConfigForm.tsx, src/components/ProjectForm/ProjectForm.tsx, src/components/ProjectForm/useConfigHook.ts, src/components/ProjectForm/utils.ts, src/constants/project.ts, src/types/imageComparison.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/277
=> feat: odiff added

src/_test/test.data.helper.ts, src/components/TestRunList/StatusFilterOperators.tsx, src/components/TestRunList/index.tsx, src/pages/ProjectPage.spec.tsx, src/types/testStatus.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/261
=> Filter operator "not-equals" for "status"

.github/workflows/workflow.yml, package-lock.json, package.json, src/Router.jsx, src/_test/stub.helper.ts, src/_test/test.data.helper.ts, src/components/Header.tsx, src/components/TestRunList/index.tsx, src/components/UserList/ActionButtons.tsx, src/components/UserList/index.tsx, src/constants/routes.ts, src/pages/ProfilePage.tsx, src/pages/UserListPage.spec.tsx, src/pages/UserListPage.tsx, src/services/users.service.ts, src/types/user.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/144
=> Add rights for users with read access

src/components/Filters.tsx, src/components/TestRunList/BulkOperation.tsx, src/components/TestVariationMergeForm.tsx, src/services/testRun.service.ts, src/services/testVariation.service.ts, src/types/ignoreArea.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/287
=> TestVariation. Allow selecting target branch to merge #287

src/services/testRun.service.ts
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/285
=> Cannot add comment - 404

package-lock.json, package.json, src/App.jsx, src/_test/test.moun.helper.tsx, src/components/Header.spec.tsx, src/components/Header.tsx, src/components/LoginForm.tsx, src/components/PrivateRoute.tsx, src/components/RegisterForm.tsx, src/components/TestDetailsDialog/ArrowButtons.tsx, src/components/TestDetailsDialog/TestDetailsModal.tsx, src/components/TestDetailsDialog/index.tsx, src/components/TestRunList/index.tsx, src/components/UserList/ActionButtons.tsx, src/components/UserList/index.tsx, src/contexts/index.ts, src/contexts/project.context.tsx, src/contexts/testRun.context.tsx, src/contexts/user.context.tsx, src/pages/LoginPage.tsx, src/pages/ProfilePage.tsx, src/pages/RegisterPage.tsx, src/types/user.ts
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/286
=> TestRun list. Next/Prev buttons ignores sorting

src/pages/TestVariationDetailsPage.tsx, src/types/baseline.ts
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/292
=> TestVariation. Cannot load data if TestRUn was deleted

src/components/TestRunList/BulkOperation.tsx
Addresses issue https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/296
=> Stop the progress bar on performing operation for unauthorized user.

src/components/TestDetailsDialog/ArrowButtons.tsx, src/components/TestDetailsDialog/TestDetailsModal.tsx, src/components/TestDetailsDialog/index.tsx, src/contexts/testRun.context.tsx
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/297
=> TestRun. Save changes prompt is shown

src/components/TestRunList/BulkOperation.tsx, src/services/testRun.service.ts
Fix for https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/346
=> Fix for #346 - Download does not download all images.

src/components/TestRunList/index.tsx
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/330
=> fix: TestRunList. Rows per page select does not work

src/components/BuildList/index.tsx
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/327
=> fix: Build List: Items are not reloaded when deleting

src/components/ProjectForm/LooksSameConfigForm.tsx
Fix for: [Visual-Regression-Tracker/issues/334](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/334)
=> fix(#334): typo dimentions -> dimensions

src/components/TestDetailsDialog/TestDetailsModal.tsx, src/components/TestDetailsDialog/index.tsx
=> Addresses issue #534 - Show progress counter.

README.md, integration_tests/fixtures/index.ts, integration_tests/pages/ProjectPage.ts, integration_tests/pages/UserListPage.ts, integration_tests/pages/components/BuildList.ts, integration_tests/pages/components/Table.ts, integration_tests/pages/components/TestRunList.ts, integration_tests/test/projec.spec.ts, src/_test/test.data.helper.ts, src/components/TestRunList/BulkOperation.tsx, src/services/static.service.ts, src/services/testRun.service.ts
related to https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/417
=> Fix download images

integration_tests/fixtures/index.ts, integration_tests/test/projec.spec.ts, package-lock.json, package.json, src/components/TestRunList/BulkOperation.tsx, src/services/static.service.ts, src/services/testRun.service.ts, src/setupTests.ts
Upgrade @testing-library/jest-dom to fix #343 and run Prettier
=> Upgrade @testing-library/jest-dom to fix security issue and run Prettier

src/components/TestRunList/BulkOperation.tsx
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/437
=> fix: Bulk approve was always a merge
