Visual-Regression-Tracker/frontend

src/App.jsx, src/components/BuildList.tsx, src/components/BuildStatusChip.tsx, src/components/TestDetailsModal.tsx, src/contexts/build.context.tsx, src/pages/ProjectPage.tsx, src/pages/TestVariationDetailsPage.tsx, src/types/build.ts, src/types/buildStatus.ts, src/types/testRun.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/23
=> 23 build status

src/pages/ProjectPage.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/36
=> height fixed

package-lock.json, package.json, src/components/DrawArea.tsx, src/components/Rectangle.jsx, src/components/TestDetailsModal.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/37
=> 37 ignore draw

src/components/BuildList.tsx, src/components/DrawArea.tsx, src/components/SkeletonList.tsx, src/components/TestDetailsModal.tsx, src/components/TestRunList.tsx, src/contexts/build.context.tsx, src/contexts/testRun.context.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/38
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/39
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/40
=> 38 loading animation

package-lock.json, package.json, src/components/CommentsPopper.tsx, src/components/DrawArea.tsx, src/components/TestDetailsModal.tsx, src/services/testRun.service.ts, src/services/testVariation.service.ts, src/types/testRun.ts, src/types/testVariation.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/47
=> Add comment

src/components/DrawArea.tsx, src/components/ImageDetails.tsx, src/components/TestDetailsModal.tsx, src/components/TestVariationDetails.tsx, src/pages/ProjectListPage.tsx, src/types/project.ts, src/types/testRun.ts, src/types/testVariation.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/69
=> branh added

src/components/Filters.tsx, src/pages/TestVariationListPage.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/70
=> Variations. branch name filter added

src/components/ProjectModal.tsx, src/contexts/project.context.tsx, src/pages/ProjectListPage.tsx, src/services/projects.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/71
=> 71 project edit

src/_helpers/route.helpers.ts, src/components/TestDetailsModal.tsx, src/components/TestVariationMergeForm.tsx, src/pages/TestVariationListPage.tsx, src/services/testRun.service.ts, src/services/testVariation.service.ts, src/types/testRun.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/72
=> approve method added with merge param

src/components/TestVariationList.tsx, src/pages/TestVariationListPage.tsx, src/services/testVariation.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/58
=> test variation delete added

package-lock.json, package.json, src/App.jsx, src/components/BuildList.tsx, src/components/LoginForm.tsx, src/components/RegisterForm.tsx, src/components/TestDetailsModal.tsx, src/components/TestRunList.tsx, src/components/TestVariationMergeForm.tsx, src/contexts/auth.context.tsx, src/contexts/build.context.tsx, src/contexts/project.context.tsx, src/contexts/testRun.context.tsx, src/pages/ProfilePage.tsx, src/pages/ProjectListPage.tsx, src/pages/ProjectPage.tsx, src/pages/TestVariationDetailsPage.tsx, src/pages/TestVariationListPage.tsx, src/services/builds.service.ts, src/services/projects.service.ts, src/services/testRun.service.ts, src/services/testVariation.service.ts, src/services/users.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/73
=> 73 register error

.gitignore, Dockerfile, env.sh, nginx/gzip.conf, package.json, public/index.html, src/_config/api.config.ts, src/_config/env.config.ts, src/contexts/socket.context.tsx, src/services/builds.service.ts, src/services/projects.service.ts, src/services/static.service.ts, src/services/testRun.service.ts, src/services/testVariation.service.ts, src/services/users.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/84
=> REACT_APP_API_URL configuration fixed

src/components/TestRunList.tsx
I have a number of images that I read from a folder. So, when I run with a new device, I get all images as new. To approve all of them, I have to click approve many times. Instead, I added an "Approve all" button which will approve all images in that run saving time.
https://user-images.githubusercontent.com/9042580/102675662-1a09be00-414f-11eb-9143-85476abf612f.mov
=> Enabled option to approve all images in a test run

src/_test/stub.helper.ts, src/contexts/testRun.context.tsx, src/pages/ProjectPage.tsx, src/services/testRun.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/180
=> TestRuns. Add pagination

src/_test/stub.helper.ts, src/components/TestRunList/index.tsx, src/contexts/testRun.context.tsx, src/services/testRun.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/213
=> Switch to client instead of server side pagination

src/components/BuildList/index.tsx, src/components/TestRunList/DataGridCustomToolbar.tsx, src/components/TestRunList/StatusFilterOperators.tsx, src/components/TestRunList/TagFilterOperators.tsx, src/components/TestRunList/index.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/194
=> Test run. Add filtering

src/contexts/socket.context.tsx, src/types/build.ts
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/256
=> Build update event does not respect selected project #256

src/components/TestDetailsModal.tsx, src/components/TestRunList/BulkOperation.tsx, src/services/testRun.service.ts
Addresses issue https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/276
Changes included:
1. Clear icon will clear ignore area of the selected images.
2. ~~Apply ignore area icon will be enabled only one selection and then on confirming apply, it will apply the selected ignore area to all images in the build.~~
3. For small number of selection, both the "wait for processing" snackbar and success snackbar come almost at the same time which may confuse users. Replace this with a progress bar under the action icons.
~~I will raise a matching backend pull request if this is approved in principal. Here are some screenshots for reference.~~
=> Issue #276: Enable to bulk clear ignore area for test runs list and details view.

src/components/TestDetailsModal.tsx, src/services/testRun.service.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/276 
Attached video. Will raise backend pull request if this is approved. Currently, it is not possible to select which test runs it needs to apply to.
https://user-images.githubusercontent.com/9042580/122833949-9e75fe80-d2a2-11eb-9116-be2fa6651b89.mov
=> Apply ignore area to all images from selected ignore area from details page.

src/components/ProjectForm/ProjectForm.tsx, src/constants/project.ts, src/types/project.ts
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/275
=> Clean up old test variations

package-lock.json, package.json, src/components/TestDetailsDialog/index.tsx, src/components/TestRunList/BulkOperation.tsx, src/components/TestRunList/DataGridCustomToolbar.tsx, src/components/TestRunList/StatusFilterOperators.tsx, src/components/TestRunList/TagFilterOperators.tsx, src/components/TestRunList/index.tsx, src/contexts/testRun.context.tsx
https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/260
=> [BUG] Arrow-keys navigation not consider filters

package-lock.json, package.json, src/components/BuildList/index.tsx, src/components/DrawArea.tsx, src/components/Header.tsx, src/components/LoginForm.tsx, src/components/RegisterForm.tsx, src/components/TestDetailsDialog/TestDetailsModal.tsx, src/components/TestRunList/index.tsx, src/contexts/testRun.context.tsx, src/pages/LoginPage.tsx, src/pages/ProfilePage.tsx, src/pages/RegisterPage.tsx
closes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/305
=> TestRun. Do not change order when details modal is shown

src/components/TestDetailsDialog/TestDetailsModal.tsx
Fixes https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/317
=> Fix for issue 317

.env, docker-compose.yml, src/_config/env.config.ts, src/_test/precondition.helper.ts, src/components/GuidedTour.tsx, src/components/Header.tsx, src/pages/ProfilePage.spec.tsx
Closes issue https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/323 
Version information is shown.
The menu item has been changed a little bit.
=> Menu item UI update and show VRT version - closes issue #323

nginx/default.conf
Resolves [Issue #366](https://github.com/Visual-Regression-Tracker/Visual-Regression-Tracker/issues/366) 
Check if the relative path is specified in require_uri and return 403 before sending the request to be resolved by the server.
```
if ($request_uri ~ "\.\./"){
return 403;
}
```
http://localhost:8080/?../../../../../../../../etc/hosts -> 403 forbidden
http://localhost:8080/?../../../../../../../../etc/passwd -> 403 forbidden
This will prevent any directory traversal attempts.
=> fix: check if relative path is specified in require_uri and return 403

src/components/DrawArea.tsx, src/components/TestDetailsDialog/TestDetailsModal.tsx, src/components/TestRunList/index.tsx, src/types/ignoreArea.ts
When image is scaled and I try to add ignored areas, area boundaries do not match cursor position.
=> Fix creating ignored areas for scaled imaged

vite.config.ts
```
vite v4.4.9 building for production...
node_modules/@mui/x-data-grid/hooks/features/filter/gridFilterUtils.js (10:12) Use of eval in "node_modules/@mui/x-data-grid/hooks/features/filter/gridFilterUtils.js" is strongly discouraged as it poses security risks and may cause issues with minification.
node_modules/@mui/x-data-grid/hooks/features/filter/gridFilterUtils.js (175:21) Use of eval in "node_modules/@mui/x-data-grid/hooks/features/filter/gridFilterUtils.js" is strongly discouraged as it poses security risks and may cause issues with minification.
✓ 12520 modules transformed.
build/index.html                                                0.61 kB │ gzip:   0.36 kB
build/assets/roboto-vietnamese-700-normal-d986b503.woff         4.73 kB …
```
=> Remove manual chunks and disable inlining assets
